### PR TITLE
Script to install azk #248 #117

### PR DESCRIPTION
**Pull request by saitodisse**
Script to easily install azk.
Issues: #248 #117

- [ ] Test in Linux
- [x] Test in Mac

### CODE REVIEW

**Comment by lucasfais** [comment]
LGTM on OS X, but I think the output should be more concise. Personally, I don't like those "banners":

```shell
**  --------------
**  Installing azk
**  --------------

* Platform detected: darwin, x64

**  -------------------
**  install_azk_mac_osx
**  -------------------

Virtual Box detected
==> Installing azk from azukiapp/homebrew-azk
==> Downloading http://repo.azukiapp.com/mac/azk_0.9.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/azk-0.9.2.tar.gz
  /usr/local/Cellar/azk/0.9.2: 9749 files, 203M, built in 11 seconds
```

I suggest something like this:

```shell
1. Checking platform
==> Platform detected: darwin, x64
2. Checking for VirtualBox installation
==> Virtual Box detected
3. Installing azk
==> Installing azk from azukiapp/homebrew-azk
==> Downloading http://repo.azukiapp.com/mac/azk_0.9.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/azk-0.9.2.tar.gz
🍺  /usr/local/Cellar/azk/0.9.2: 9749 files, 203M, built in 11 seconds
```

What do you think guys?

**Comment by gullitmiranda** [comment]
I'm liked your suggestion @lucasfais.

**Comment by heitortsergent** [comment]
:+1: on @lucasfais suggestion

**Comment by nuxlli** [comment]
Good suggestion @lucasfais, personally think that the banners are "verbose", on the one hand the terminal gets dirty on the other become less trivial to implement script on the install script.

**Comment by saitodisse** [comment]
migrated to https://github.com/azukiapp/azk/pull/295

**Pull request closed without merging**
