### PR TITLE
[system_dns] Fixing support to dns_servers

### PR DESCRIPTION
**Pull request by gullitmiranda**
Fixing support to dns_servers (PR #273 )

To test:

- Add custom `dns_servers` in Azkfile.js:

```js
systems({
  'web': {
    image: "azukiapp/node",
    command: "node index.js",
    workdir: "/azk/#{manifest.dir}",
    http: {
      domains: [ "#{system.name}.#{azk.default_domain}" ],
    },
    dns_servers: ['208.67.222.222', '208.67.222.220']
  },
});
```

- Run `azk shell` and check `/etc/resolv.conf` file:

```sh
$ azk shell
# cat /etc/resolv.conf
nameserver 192.168.50.4
nameserver 208.67.222.222
nameserver 208.67.222.220
```

### CODE REVIEW

**Comment by saitodisse** [comment]
LGTM

**Comment by lucasfais** [comment]
It works as you described, but I think there is a *gotcha* here.

I put in my `Azkfile.js`:
```js
//...
    dns_servers: ['8.8.8.8'],
//...
```

As you described:

```sh
root@bc0d7193488b:/azk/myapp# cat /etc/resolv.conf
nameserver 192.168.50.4
nameserver 8.8.8.8
```

However, considering that `/etc/resolv.conf`, the primary DNS server is `192.168.50.4` (the azk DNS server):

```shell
root@bc0d7193488b:/azk/myapp# nslookup google.com
Server:		192.168.50.4
Address:	192.168.50.4#53

Non-authoritative answer:
Name:	google.com
Address: 200.233.62.84
# ...
Name:	google.com
Address: 200.233.62.106
```

Note who answered the the DNS request... `Address:	192.168.50.4#53`. So the `8.8.8.8` isn't being used.

Maybe, that problem should be a little complicated to solve because all azk containers should use the azk DNS server to access each other. Am I right @nuxlli?

**Comment by nuxlli** [comment]
@lucasfais you are not wrong about the behavior, but there is no error here, the behavior is expected.

What happens is this: that the containers within the implementation structure of `azk` they can find you must add the address of the DNS server, otherwise a container would not be able to correctly resolve the address of "web.dev.azk.io" for example.

Before you continue you need to quickly examine how addresses are resolved within a Linux machine: basically when a resolution a message is necessary `udp` is sent to all nameservers listed in `/etc/resolv.conf`, those who answer this message in a more "agile" shall have priority and shall go be used. (Note: the `nslookup` is not a good reference for your resolution process happens in a different way from the standard resolution of other applications).

Internally the `azk` is used the `dnsmasq` as a solution for DNS resolutions, `dnsmasq` is a robust solution which was added to Ubuntu 12.04, as a smarter way to dns resolution and custom namservers management on those informed by dhcp network: http://unix.stackexchange.com/a/59424/38871

Finally there is in my view no obstacle in the way we are using the DNS system in `azk`, for those cases where a internal server is custom in "Azkfile.js" our "dnsmasq" will fail (because it not know how to solve that domain) and custom server will succeed.

**Comment by saitodisse** [comment]
Very good discussion :+1:

**Pull request merged**
