### PR TITLE
Update node, update npm and fixing shirinkwrap in package

### LINKED ISSUE #285: [npm] Replace `npm shrinkwrap` with `npm lockdown`
## REFERENCES:

- https://www.npmjs.com/package/lockdown
- https://github.com/mozilla/npm-lockdown

### PR DESCRIPTION
**Pull request by nuxlli**
This pull request closes #285 issue.

This a node update (`0.10.36`) patch but also adds a tasks that updates NPM after installing node.

Beyond theses updates it also modifies the `Makefile.js` to generate the specific azk `npm-shirinkwrap.json` packages during the packaging process, containing only `production` dependencies, without touching the main azk's `npm-shirinkwrap.json`.

Theses changes in turn make it unnecessary to use `lockdown` as proposed in #285

### CODE REVIEW

**Comment by saitodisse** [comment]
:+1:  very good @nuxlli

**Comment by nuxlli** [comment]
@nuxlli I missed changelog :P

**Comment by gullitmiranda** [comment]
LGTM!

**Comment by saitodisse** [comment]
LGTM!

**Pull request merged**
