### PR TITLE
[Dockerfile] Fixing `azk build` does not support `COPY` in Dockerfile

### LINKED ISSUE #341: [docker] `azk build` does not support `COPY` in Dockerfile
azk image builder does not support the command `COPY`

```
FROM azukiapp/azktcl:0.0.2
MAINTAINER Azuki <support@azukiapp.com>

COPY copy-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```

fix: https://github.com/azukiapp/azk/blob/master/src/docker/build.js#L48

Thanks @rafaelverger for the report.

### LINKED ISSUE #342: [docker] `azk build` does not support url in `COPY` or `ADD` in Dockerfile
**e.g.:**
```
FROM azukiapp/ubuntu

ADD http://azk.io/install.sh /install_azk.sh
RUN chmod +x /install_azk.sh
CMD ["/install_azk.sh"]
```

### PR DESCRIPTION
**Pull request by gullitmiranda**
This pull request closes #341 and closes #342 issues.

### CODE REVIEW

**Comment by saitodisse** [comment]
LGTM :+1:

**Comment by fearenales** [comment]
ok to test

**Comment by fearenales** [comment]
ok to test

**Comment by fearenales** [comment]
ok to test

**Comment by fearenales** [comment]
ok to test

**Pull request merged**
