### PR TITLE
Feature/128 system inheritance

### PR DESCRIPTION
**Pull request by saitodisse**
### `extends`, Azkfile.js system inheritance #128

Suporting inheritance directly on Azkfile.js without any javascript magic:

Example:
```js
systems({
  "example": {
    depends: ["db", "api"],
    workdir: '/azk/#{manifest.dir}',
    image: default_img,
    mounts: mounts_with_persitent,
    scalable: { default: 3 },
    http: true,
    command, provision,
    envs: {
      ECHO_DATA: "data"
    }
  },
  "example-extends": {
    extends: "example",
    // equals example but with only one scalable instance
    scalable: { default: 1 },
  },
});
```

### CODE REVIEW

**Comment by lucasfais** [comment]
I executed a  test with the `Azkfile.js` below:

```js
systems({
  node010: {
    depends: [],
    image: {"docker": "node:0.10"},
    provision: [
      "npm install",
    ],
    workdir: "/azk/#{manifest.dir}",
    shell: "/bin/bash",
    command: "npm start",
    wait: {"retry": 20, "timeout": 1000},
    mounts: {
      '/azk/#{manifest.dir}': path("."),
    },
    scalable: {"default": 2},
    http: {
      domains: [ "#{system.name}.#{azk.default_domain}" ]
    },
    envs: {
      NODE_ENV: "dev",
    },
  },
  other: {
    extends: "node010",
    env: {
      NODE_ENV: "production",
    }, 
  }
});
```

Note that I changed the `NODE_ENV` variable to `production` inside `other` system. Looking for the `NODE_ENV` variable in `azk shell`, it remains with `dev` value.

```sh
$ azk shell other
root@4d04be4c66cb:/azk/node010# echo $NODE_ENV
dev
```

`NODE_ENV` should be `production`, right?

**Comment by lucasfais** [comment]
Oh sorry... my mistake! 

`env` should be `envs`!

**Comment by gullitmiranda** [comment]
:+1:

**Comment by lucasfais** [comment]
Everything working fine on OS X... lgfm!

**Comment by heitortsergent** [comment]
LGTM :+1:

**Comment by heitortsergent** [comment]
:+1:

**Pull request merged**
