### PR TITLE
[cli] Fixing duplicated options, actions or arguments in help controller

### PR DESCRIPTION
**Pull request by gullitmiranda**
The lib `cli-router@0.3.5` has a bug in help display that duplicates all options that have the '=' sign in [`shared/locales/usage-en-US.txt`](https://github.com/azukiapp/azk/blob/master/shared/locales/usage-en-US.txt).
e.g.: `azk start [system] [--log = <level> ] ...`

By upgrading to `v0.3.6` it was resolved.

### CODE REVIEW

**Comment by saitodisse** [comment]
LGTM :+1:

**Comment by fearenales** [comment]
@gullitmiranda, in the usage, there are options that aren't in POSIX standard, like `-l=<level>`. The correct would be `-l <level>` (as it was before).

From docopt docs:
```
    - Short options can be "stacked" meaning that -abc is equivalent to -a -b -c.
    - Long options can have arguments specified after space or equal "=" sign:
    --input=ARG is equivalent to --input ARG.
    - Short options can have arguments specified after optional space:
    -f FILE is equivalent to -fFILE.
```

So, `--log=<level>` is ok, but `-l=<level>` is not.

**Comment by gullitmiranda** [comment]
@fearenales I had not noticed that detail. I will make the changes.

**Comment by fearenales** [comment]
@gullitmiranda I've just pushed the fix ;)

**Comment by gullitmiranda** [comment]
nice, thanks

**Pull request merged**
