### PR TITLE
[tracking] Fixing timeout message when tracking an event

### LINKED ISSUE #390: error: TimeoutError when stopping elasticsearch
```
$ azk stop elasticsearch
azk: ↓ stopping `elasticsearch` system, 1 instances...
error: TimeoutError: operation timed out
    at afterTimeout (/usr/local/Cellar/azk/0.12.1/node_modules/insight-keen-io/node_modules/bluebird/js/main/timers.js:11:15)
    at [object Object].timeoutTimeout (/usr/local/Cellar/azk/0.12.1/node_modules/insight-keen-io/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
error: TimeoutError: operation timed out
    at afterTimeout (/usr/local/Cellar/azk/0.12.1/node_modules/insight-keen-io/node_modules/bluebird/js/main/timers.js:11:15)
    at [object Object].timeoutTimeout (/usr/local/Cellar/azk/0.12.1/node_modules/insight-keen-io/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

┌───┬───────────────┬───────────┬──────────────┬─────────────────┬─────────────┐
│   │ System        │ Instances │ Hostname/url │ Instances-Ports │ Provisioned │
├───┼───────────────┼───────────┼──────────────┼─────────────────┼─────────────┤
│ ↓ │ elasticsearch │ 0         │ dev.azk.io   │ -               │ -           │
└───┴───────────────┴───────────┴──────────────┴─────────────────┴─────────────┘
```

### PR DESCRIPTION
**Pull request by fearenales**
This PR closes #390 

Instead of a say-nothing stack trace, when tracking an event fails, a specific message should be properly logged using the `info` level.
This allow the user to know when tracker times out but doesn't show error messages by default.

### CODE REVIEW

**Comment by fearenales** [comment]
ok to test

**Comment by gullitmiranda** [comment]
@fearenales 
Normally we use the [`errors.js`](https://github.com/azukiapp/azk/blob/master/src%2Futils%2Ferrors.js) along with [`en-US.js`](https://github.com/azukiapp/azk/blob/master/shared%2Flocales%2Fen-US.js#L30-L102) to concentrate all error messages. I think we should continue to follow the same pattern.

**Comment by fearenales** [comment]
you're right @gullitmiranda ! I'll submit one more commit regard this soon.

**Comment by heitortsergent** [comment]
@fearenales added a commit to your branch :dancer:

**Comment by fearenales** [comment]
Thank you so much @heitortsergent ! :)

**Pull request merged**
