### PR TITLE
[WIP] Remove dependency on VirtualBox

### PR DESCRIPTION
**Pull request by SomeoneWeird**
1. What is this PR objective?

Allows you to use native docker (xhyve on macOS) and not rely on virtualbox

### CODE REVIEW

**Comment by fearenales** [comment]
Hi @SomeoneWeird, thank you for your initiative!

About azk and Docker for Mac, we have to make several changes on azk to adapt to it:
- Remove all logic from agent to handle the VM: we use VirtualBox and azk is responsible to manage it. Docker for Mac uses xhyve (https://github.com/mist64/xhyve) under the hood, but azk won't handle it anymore);
- Create a profile at azk configure (https://github.com/azukiapp/azk/blob/master/src/agent/configure.js) to properly handle local Docker directly on Mac;
- Fix port issues, since those ports won't be related to the VM anymore;
- Fix `sync()` mount option, since the VM won't exist anymore.

Any help you may need, please just let us know.

**Comment by SomeoneWeird** [comment]
Yep, marked as WIP for a reason :) I should be able to spend some time on this over the next week or two.

1 & 2) Docker for mac should be nearly exactly the same as linux, I'm not sure there's anything special we need to do there?

3 & 4) Good point, I didn't think about those, I'll have a look :)

**Comment by terto** [comment]
Hi guys, I'm looking forward by this PR, I'd like to use azk without virtualbox in my mac os

Cheers

**Comment by BlueHotDog** [comment]
Hi, likewise, very very important for me as well!

**Comment by SomeoneWeird** [comment]
Not working on this anymore.

**Pull request closed without merging**
