### PR TITLE
[kernel] Updating `vboxmanage` to fix parse in Virtual Box 5.0

### LINKED ISSUE #481: Do not work on VirtualBox 5
```
$ VBoxManage --version
5.0.0r101573

$ azk vm  status -vvvv

/usr/local/Cellar/azk/0.14.4/node_modules/vboxmanage/lib/parse.js:97
      return JSON.parse("{" + line + "}");
                  ^
SyntaxError: Unexpected token @
    at Object.parse (native)
    at to_item (/usr/local/Cellar/azk/0.14.4/node_modules/vboxmanage/lib/parse.js:97:19)
    at Array.map (native)
    at Object.exports.machinereadable_list (/usr/local/Cellar/azk/0.14.4/node_modules/vboxmanage/lib/parse.js:99:30)
    at /usr/local/Cellar/azk/0.14.4/node_modules/vboxmanage/lib/machine.js:47:37
    at Object.callback (/usr/local/Cellar/azk/0.14.4/node_modules/vboxmanage/lib/command.js:72:16)
    at next (/usr/local/Cellar/azk/0.14.4/node_modules/vboxmanage/node_modules/async/lib/async.js:720:43)
    at /usr/local/Cellar/azk/0.14.4/node_modules/vboxmanage/node_modules/async/lib/async.js:24:16
    at ChildProcess.<anonymous> (/usr/local/Cellar/azk/0.14.4/node_modules/vboxmanage/lib/command.js:64:20)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

### LINKED ISSUE #502: SyntaxError: Unexpected token @
Hi, I'm trying to start my azk env and I getting this error.

MacBook Pro (Retina, 15-inch, Mid 2015)
Node: 0.12.7
npm:2.12.1 

```
$ azk agent start
azk: Wait, this process may take several minutes
azk: Loading settings and checking dependencies.
azk: Checking version...
azk: azk 0.14.5 detected

/usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/lib/parse.js:97
      return JSON.parse("{" + line + "}");
                  ^
SyntaxError: Unexpected token @
    at Object.parse (native)
    at to_item (/usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/lib/parse.js:97:19)
    at Array.map (native)
    at Object.exports.machinereadable_list (/usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/lib/parse.js:99:30)
    at /usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/lib/machine.js:47:37
    at Object.callback (/usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/lib/command.js:72:16)
    at next (/usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/node_modules/async/lib/async.js:720:43)
    at /usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/node_modules/async/lib/async.js:24:16
    at ChildProcess.<anonymous> (/usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/lib/command.js:64:20)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

### PR DESCRIPTION
**Pull request by gullitmiranda**
This PR closes #481, closes #502 .

In Virtual Box 5.0, there is a slight change in the ouput of the command `VBoxManage showvminfo azk-vm-dev.azk.io --machinereadable`:

```
# Virtual Box < v5.0:
VideoMode="720,400,0"@0,0
# Virtual Box v5.0:
VideoMode="720,400,0"@0,0 1
```

Updating [gullitmiranda/node-vboxmanage](https://github.com/gullitmiranda/node-vboxmanage), this isse was solved.

### CODE REVIEW

**Comment by fearenales** [comment]
LGTM

**Comment by t3hk0d3** [comment]
Guys, its serious issue. Please pull this PR.

**Comment by gullitmiranda** [comment]
You're right @t3hk0d3.
We are doing the testing and final adjustments to launch a release with a new version of azk (`v0.15.0`).

**Comment by fearenales** [comment]
@t3hk0d3: The fix for this issue is available in azk v0.14.6.
May you check if this worked for you?

Thank you for your support!

**Pull request merged**
