### PR TITLE
[Docker] If running inside vm, do not monitor Docker

### LINKED ISSUE #525: Azk agent not running
I have a few running services inside azk vm and a few azk shells started, which I can access.

The http loadbalancer stopped working (connection reset by peer), and azk status says that agent is not running. However, the containers are open and running. Any ideas ? In the last few days I had a lot of problems with azk (last 2 versions, 0.14.4 and 0.15.0), the vm stopped completely on system sleep twice. 

Before, on azk 0.12.1 everything was fine.

Are there any logs I can paste here ?

```
$ azk status
? The agent is not running, would you like to start it? No
azk: azk agent is required but is not running (try `azk agent status`)
```

### PR DESCRIPTION
**Pull request by teodor-pripoae**
This PR closes #525.

Add `AZK_DOCKER_MONITOR` env var which defaults to true if running on linux.

### CODE REVIEW

**Comment by fearenales** [comment]
LGTM

**Comment by fearenales** [comment]
ok to test

**Comment by fearenales** [comment]
Sync tests failing at CI. Further investigation needed.

**Comment by fearenales** [comment]
I've Just tested it again at CI box and everything went well. Looks like an intermittent error.

**Comment by fearenales** [comment]
@teodor-pripoae we've mentioned this PR on the azk v0.16.0 release blog post.
https://medium.com/azuki-news/azk-v-016-0-building-together-8b41f455a59d

On behalf of azk core team, I'd like to say thank you!

**Comment by teodor-pripoae** [comment]
Thank you !

**Pull request merged**
