### PR TITLE
Updating `azk-dev` and other related dependencies

### PR DESCRIPTION
**Pull request by nuxlli**
The main contribution on this PR is updating the `azk-dev` lib. This brings, among other improvements, `babel 6.x` version. In few words, those changes on `babel` make the source code transpilation process more modular.

* Updating `azk-dev`:
  - Changes on `azk-dev` modules calls, from `azk/gulp` to `azk/lib/gulp`, as instance. The former pattern is still supported but has been deprecated: 30409279067a94ebc6e50e1cccfe2f1e4d569861;
  - The order in which the `chai` plugins are loaded was changed. Now, it's possible to combine `chai-as-promised` and `chai-subset`. This is not part of `azk` anymore: 03658bc09c4d2c390b650cd5e9709075386bc475;
  - Replacing the system of support to generators  (directly in the `it` methods) with a system from `azk-dev`, which is simpler and better supported 03658bc09c4d2c390b650cd5e9709075386bc475;
  - In `bluebird > 3.0`, the method `promisify` was changed and no longer supports the return of multiple actions (aka: Array expansion). This has caused a big impact and led to replacing many `nfcall` and `nbind` by direct calls to `promisify` with the option `{ multiArgs: true }` ec5f0e6998f7ce13f8e41aa84c2c5182caff97ea;
  - While solving the previous problem, we've noticed a problem with the error handling during the VM start on agent. It was fixed, so now it's easier to identify them e67e8e360e0d5232aa3366166602eeb0d8f7a87e;
  - Finally, for a matter of simplification and better support to the modules scheme from ES6, the use of the instructions `export`, `export default` and `import` was improved 30409279067a94ebc6e50e1cccfe2f1e4d569861;

* Updating `lodash`:
  - `template` now generates a "compiled template", returning a method to expand it. The `src/utils` was updated to attend this new API. More at c5f532f60c2d636520ce42f5b80c517c2c33718f;
  - By default, `flatten` no longer does `deep flaten`. To do so, the option `true` must be passed. In this case, the change was bigger once the problem occured in `src/cmd/start.js` and it was noticed there were better approaches in the class `Manifest` to get the system list and its dependencies. More at 318c9bead11023c5fa18699bd056799e3f329120;
  - While solving the problem with `template`, it was identified an issue on the specification of `ManifestError` which turned the debbuging process more harsh. To solve this, a `type` was added to the error in order to identify it adc9e5f12bcd473ec643fe5c00ae7d442e316a1f;
  - A change in the function `merge` brought a problem in processing the parameters to be sent to the Docker during the execution of the steps of provision or execution of a `azk shell`. A change to "assign" fixed the problem: e67237a15fd4a53849140858047dfc01ba4a217d;

* Updating `insight-keen-io`, removing support to promises. Instead, default node callbacks are used b60247a3a9e7f8ce93bd3ce9249310f4282efd17;

* Other updates with minor impact: `archiver`, `crash-report-sender`, `docker-registry-downloader`, `file-async` and `inquirer` f25e06736fc66bf3ccc552cd431bd050b8e4804b;

### CODE REVIEW

**Comment by saitodisse** [comment]
LGTM

**Comment by saitodisse** [comment]
LGTM :ok:

**Comment by fearenales** [comment]
LGTM

**Comment by gullitmiranda** [comment]
LGTM

**Pull request merged**
