### PR TITLE
[Cli] azk start github again

### PR DESCRIPTION
**Pull request by saitodisse**
Before when `azk start URL` and the destination folder exists we get an error.
Now, when destination exists pulls again from git remote server and continue.

image

### CODE REVIEW

**Comment by fearenales** [comment]
@saitodisse I didn't specify the destination folder and ended up with this error:

```
$ azk start https://github.com/saitodisse/azkdemo#two -vvvv
```

screenshot from 2015-07-31 18-39-37

**Comment by saitodisse** [comment]
I didnt know that `git pull` not acept relative folder. I going to fix this

**Comment by gullitmiranda** [comment]
Running again, this behavior is right?

```shell
$ azk start https://github.com/saitodisse/azkdemo\#two
azk: Checking Git version...
azk: Getting remote info from `https://github.com/saitodisse/azkdemo`...
azk: Checking `azkdemo` exists...
azk: Pulling changes from remote server...
azk: The `wait` used in `azkdemo` is deprecated, check the documentation for `wait`
azk: System `azkdemo` already started
```

**Comment by saitodisse** [comment]
@gullitmiranda, this is the expected behaviour.
You can run with `verbose` to see commands executed.

**Comment by gullitmiranda** [comment]
I understand, but in the case of `azk start` with URL, the behavior must be different, that is, if the system is already running, it restarts. Does not agree?

Another interesting thing also, in my opinion, is to have an option to "customize" to the command to run.

**Pull request merged**
