### PR TITLE
[updating_install.sh] Adding instructions to install.sh disable dnsmasq

### PR DESCRIPTION
**Pull request by fearenales**
This PR includes:
* `install.sh` now disables `dnsmasq`;
* improving `install.sh` log messages;
* updating docs (replacing `init.d`scripts with a `service` command to disable `dnsmasq`);

### CODE REVIEW

**Comment by gullitmiranda** [comment]
:+1:

**Comment by fearenales** [comment]
ok to test

**Comment by fearenales** [comment]
ok to test

**Comment by gullitmiranda** [comment]
LGTM. :+1:

**Comment by saitodisse** [comment]
LGTM
image

**Pull request merged**
