### PR TITLE
[update_suggestions] Update suggestions images, rails, ruby, mysql. #224 #218

### PR DESCRIPTION
**Pull request by gullitmiranda**
* Make and use [`azukiapp/mysql`](https://registry.hub.docker.com/u/azukiapp/mysql/) docker image.
* Adding `ruby 2.0` and `ruby 2.2` versions to [ `azukiapp/ruby`](https://registry.hub.docker.com/u/azukiapp/ruby/) docker image.
* Changing `rails` suggestions to use [ `azukiapp/ruby`](https://registry.hub.docker.com/u/azukiapp/ruby/) docker image.
* Fix issues #224 and #218.

### CODE REVIEW

**Comment by lucasfais** [comment]
#224 and #218 seem fixed, but there is a side effect changing `rails` to `ruby` image: 

The `ruby` image doesn't have `sqlite3` headers, so executing a "Hello World" in `rails` as described in #224, it fails when doing a `bundle install` in the provision phase.

The problem is easily replicated executing the steps below:

```shell
$ azk shell --image azukiapp/ruby --shell /bin/bash
root@05a3b9002013:/azk/rails42# gem install sqlite3
Fetching: sqlite3-1.3.10.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing sqlite3:
	ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby extconf.rb
checking for sqlite3.h... no
```

**Comment by gullitmiranda** [comment]
You're right.
I will update the ruby father image to add support sqlite3. But it interferes suggestions only indirectly.

For the future this and other problems such as deleted images, I will change all our suggestions for images created by azukiapp thus ensure the consistency of our suggestions.

**Comment by nuxlli** [comment]
@gullitmiranda :+1:

**Comment by gullitmiranda** [comment]
@lucasfais I updated the image, now the sqlite3 is already installed.

**Comment by lucasfais** [comment]
LGTM :+1:

**Pull request merged**
