### PR TITLE
[system_log_error] Distinguish azk error from sub-system log error

### LINKED ISSUE #267: Distinguish azk error from sub-system log error
This would be an improvement in `azk [res]start` errors output.

from this:
image

to that:
image

----------------

I believe that the line below on `throwRunError` function in`/azk/src/system/run.js` can improve the output:

```js
// distinguish system log output
log = log.replace(/^/gm, ' .' + system.name + ' [log] >  ');
```

### PR DESCRIPTION
**Pull request by gullitmiranda**
This pull request closes #267 issue.
More info in #267.

**eg:**
image

### CODE REVIEW

**Comment by saitodisse** [comment]
LGTM :+1:

**Comment by fearenales** [comment]
ok to test

**Comment by fearenales** [comment]
ok to test

**Comment by fearenales** [comment]
ok to test

**Pull request merged**
